functionality:
  name: maxquant_to_h5ad
  namespace: convert
  arguments:
    - name: "--input"
      type: file
      required: true
      example: /path/to/output_dir
    - name: "--output"
      type: file
      required: true
      example: output.h5ad
  resources:
    - type: r_script
      path: script.R
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    # setup:
    #   - type: python
    #     packages: [ anndata ]
    #   - type: r
    #     packages: [ anndata ]