functionality:
  name: maxquant_to_h5ad
  namespace: convert
  description: Converting a MaxQuant output folder to an AnnData file.
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      type: file
      required: true
      example: /path/to/output_dir
      description: The output folder of a MaxQuant analysis. Must contain 'combined' as a subdirectory.
    - name: "--output"
      type: file
      required: true
      direction: output
      example: output.h5ad
      description: The dataset as an AnnData file.
  resources:
    - type: python_script
      path: script.py
  test_resources:
    - type: python_script
      path: test.py
    - path: ../../../resources_test/zenodo_4274987
platforms:
  - type: docker
    image: dataintuitive/randpy:r4.0_py3.8_bioc3.12
    # setup:
    #   - type: python
    #     packages: [ anndata ]
    #   - type: r
    #     packages: [ anndata ]
  - type: nextflow
    variant: vdsl3