functionality:
  name: msgf
  namespace: msgf
  description: Perform a sequence database search with mostly default parameters.
  usage: java -Xmx3500M -jar MSGFPlus.jar --input file1.raw --reference ref.fasta --output out/
  authors:
    - name: Kenneth Verheggen
      email: kenneth@data-intuitive.com
      roles: [ maintainer ]
      props: { github: KennethVerheggen }
  argument_groups:
    - name: Inputs
      arguments:
        - name: "--input"
          type: file
          required: true
          description: One or more input mzml files
          example: input.mzml
    - name: Outputs
      arguments:
        - name: "--output"
          type: file
          required: true
          direction: output
          description: The output mzID file
          example: output.mzid
    - name: Reference sequences
      description: The sequence database (FASTA format)
      arguments:
        - name: "--fasta"
          type: file
          required: true
          example: reference.fasta
          description: A reference file in fasta format.
    - name: Configuration file
      description: The msgf config
      arguments:
        - name: "--conf"
          type: file
          required: true
          example: param.txt
          description: A config file
  resources:
    - type: bash_script
      path: script.sh
  test_resources:
    - type: bash_script
      path: test.sh
    - path: ../../resources_test/msgf_demo_files
platforms:
  - type: docker
    image: amazoncorretto:latest
    setup:
      - type: yum
        packages: [ wget, unzip, apt-transport-https ]
      - type: docker
        run: 
          - mkdir /msgf && cd /msgf &&
            wget -q https://github.com/MSGFPlus/msgfplus/releases/download/v2022.04.18/MSGFPlus_v20220418.zip -O MSGFPlus_v20220418.zip &&
            unzip MSGFPlus_v20220418.zip -d /msgf && 
            rm MSGFPlus_v20220418.zip

