functionality:
  name: "maxquant_to_h5ad"
  namespace: "convert"
  version: "main_build"
  authors:
  - name: "Robrecht Cannoodt"
    email: "rcannood@gmail.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  - name: "Kenneth Verheggen"
    email: "kenneth@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "KennethVerheggen"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives: []
    description: "The output folder of a MaxQuant analysis. Must contain 'combined'\
      \ as a subdirectory."
    example:
    - "/path/to/output_dir"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "The dataset as an AnnData file."
    example:
    - "output.h5ad"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Converting a MaxQuant output folder to an AnnData file."
  test_resources:
  - type: "python_script"
    path: "test.py"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/zenodo_4274987"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "dataintuitive/randpy:r4.0_py3.8_bioc3.12"
  target_organization: "czbiohub/mspipelines"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/czbiohub/mspipelines"
  setup: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/mspipelines/mspipelines/src/convert/maxquant_to_h5ad/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/mspipelines/mspipelines/target/docker/convert/maxquant_to_h5ad"
  executable: "/home/runner/work/mspipelines/mspipelines/target/docker/convert/maxquant_to_h5ad/maxquant_to_h5ad"
  viash_version: "0.6.6"
  git_commit: "4fef684fb8dcb2578f7009350f834d836d01d90e"
  git_remote: "https://github.com/czbiohub/mspipelines"
