functionality:
  name: maxquant
  namespace: maxquant
  description: Perform a MaxQuant analysis with mostly default parameters.
  usage: maxquant --input file1.raw --input file2.raw --reference ref.fasta --output out/
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  arguments:
    - name: "--input"
      type: file
      required: true
      multiple: true
      description: One or more Thermo Raw files.
      example: input.raw
    - name: "--reference"
      type: file
      required: true
      example: reference.fasta
      description: A reference file in fasta format.
    - name: "--output"
      type: file
      direction: output
      required: true
      example: output_dir
      description: An output directory to store the 'mqpar.xml' and 'combined' outputs.
  resources:
    - type: python_script
      path: script.py
platforms:
  - type: docker
    image: ubuntu:20.04
    setup:
      - type: apt
        packages: [ wget, unzip, apt-transport-https ]
      - type: docker
        run: 
          - wget https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb &&
              dpkg -i packages-microsoft-prod.deb &&
              rm packages-microsoft-prod.deb
      - type: apt
        packages: [ dotnet-sdk-2.1, aspnetcore-runtime-2.1, dotnet-sdk-3.1, aspnetcore-runtime-3.1 ]
      - type: docker
        run: 
          - mkdir /maxquant && cd /maxquant &&
            wget http://computproteomics.bmb.sdu.dk/share/MaxQuant_2.0.3.0.zip -O MaxQuant_2.0.3.0.zip &&
            unzip MaxQuant_2.0.3.0.zip && 
            rm MaxQuant_2.0.3.0.zip &&
            cd $(find /maxquant/* -type d -maxdepth 1) && 
            mv * /maxquant
      - type: apt
        packages: [ python3, python-is-python3 ]
  - type: nextflow
    publish: true
    labels: [ highmem, highcpu ]