functionality:
  name: "fastadl"
  namespace: "proteomics"
  version: "main_build"
  authors:
  - name: "Kenneth Verheggen"
    email: "kenneth@data-intuitive.com"
    roles:
    - "maintainer"
    props:
      github: "KennethVerheggen"
  inputs: []
  outputs: []
  arguments:
  - type: "string"
    name: "--taxid"
    alternatives: []
    description: "The taxonomyID to obtain a fasta for"
    example:
    - "9606"
    default: []
    required: true
    choices: []
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "An output directory for the fasta files"
    example:
    - "db"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "boolean"
    name: "--include_contaminants"
    alternatives: []
    description: "Include a collection of common contaminants from thegpmdb (highly\
      \ advised)"
    example: []
    default:
    - true
    required: false
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "python_script"
    path: "script.py"
    is_executable: true
  description: "Downloads a Fasta sequence database for a given taxonomy ID"
  usage: "fastadl --taxid 9606 --output db/"
  test_resources:
  - type: "bash_script"
    path: "test.sh"
    is_executable: true
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "python:3.8"
  target_organization: "czbiohub/mspipelines"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/czbiohub/mspipelines"
  setup:
  - type: "python"
    user: false
    packages: []
    pip: []
    pypi:
    - "requests"
    git: []
    github: []
    gitlab: []
    mercurial: []
    svn: []
    bazaar: []
    url: []
    script: []
    upgrade: true
  test_setup: []
info:
  config: "/home/runner/work/mspipelines/mspipelines/src/proteomics/fastadl/config.vsh.yaml"
  platform: "docker"
  output: "/home/runner/work/mspipelines/mspipelines/target/docker/proteomics/fastadl"
  executable: "/home/runner/work/mspipelines/mspipelines/target/docker/proteomics/fastadl/fastadl"
  viash_version: "0.6.6"
  git_commit: "fdc3a0dc2d0da20cde972e916794b323586dc5bd"
  git_remote: "https://github.com/czbiohub/mspipelines"
