functionality:
  name: "thermo_to_mzml"
  namespace: "convert"
  version: "0.3.3"
  authors:
  - name: "Robrecht Cannoodt"
    email: "rcannood@gmail.com"
    roles:
    - "maintainer"
    props:
      github: "rcannood"
      orcid: "0000-0003-3641-729X"
  inputs: []
  outputs: []
  arguments:
  - type: "file"
    name: "--input"
    alternatives: []
    description: "A Thermo Raw file."
    example:
    - "input.raw"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "input"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  - type: "file"
    name: "--output"
    alternatives: []
    description: "Path to an .mzML file."
    example:
    - "output.mzML"
    default: []
    must_exist: true
    create_parent: true
    required: true
    direction: "output"
    multiple: false
    multiple_sep: ":"
    dest: "par"
  argument_groups: []
  resources:
  - type: "bash_script"
    path: "script.sh"
    is_executable: true
  description: "Convert a thermo raw to an mzML file."
  usage: "thermo_to_mzml --input file1.raw --output output.mzML"
  test_resources:
  - type: "bash_script"
    path: "run_test.sh"
    is_executable: true
  - type: "file"
    path: "../../../resources_test/zenodo_4274987/raw"
  status: "enabled"
  requirements:
    commands: []
  set_wd_to_resources_dir: false
platforms:
- type: "docker"
  id: "docker"
  image: "mono:6.12"
  target_organization: "czbiohub/mspipelines"
  target_registry: "ghcr.io"
  namespace_separator: "_"
  resolve_volume: "Automatic"
  chown: true
  port: []
  setup_strategy: "ifneedbepullelsecachedbuild"
  run_args: []
  target_image_source: "https://github.com/czbiohub/mspipelines"
  setup:
  - type: "apt"
    packages:
    - "wget"
    - "unzip"
    interactive: false
  - type: "docker"
    resources: []
    label: []
    add: []
    copy: []
    run:
    - "mkdir -p /var/local/thermorawfileparser && \\\ncd /var/local/thermorawfileparser\
      \ && \\\nwget https://github.com/compomics/ThermoRawFileParser/releases/download/v1.3.4/ThermoRawFileParser.zip\
      \ && \\\nunzip ThermoRawFileParser.zip && \\\nrm ThermoRawFileParser.zip\n"
    build_args: []
    env: []
  test_setup: []
- type: "nextflow"
  id: "nextflow"
  variant: "vdsl3"
  directives:
    accelerator: {}
    conda: []
    containerOptions: []
    label: []
    module: []
    pod: []
    publishDir: []
    queue: []
    tag: "$id"
  auto:
    simplifyInput: true
    simplifyOutput: true
    transcript: false
    publish: false
  debug: false
  container: "docker"
info:
  config: "/home/runner/work/mspipelines/mspipelines/src/convert/thermo_to_mzml/config.vsh.yaml"
  platform: "nextflow"
  output: "/home/runner/work/mspipelines/mspipelines/target/nextflow/convert/thermo_to_mzml"
  executable: "/home/runner/work/mspipelines/mspipelines/target/nextflow/convert/thermo_to_mzml/thermo_to_mzml"
  viash_version: "0.6.6"
  git_commit: "4fef684fb8dcb2578f7009350f834d836d01d90e"
  git_remote: "https://github.com/czbiohub/mspipelines"
