# built for MSDIAL 4.9.0 635b1bf90092a1a0631bf2da122c69787511a11b
functionality:
  name: msdial_gcms
  namespace: msdial
  authors:
    - name: Robrecht Cannoodt
      email: rcannood@gmail.com
      roles: [ maintainer ]
      props: { github: rcannood, orcid: "0000-0003-3641-729X" }
  inputs:
    - name: "--input"
      type: file
      required: true
      multiple: true
      description: One or more ABF files.
      example: input.abf
      multiple_sep: ";"
  outputs:
    - name: "--output"
      type: file
      direction: output
      required: true
      example: output_dir
      description: An output directory to store the '*.msdial' outputs.
  arguments:
    # input parameters
    - name: "--name"
      type: string
      required: false
      multiple: true
      example: [foo, bar, baz]
      description: Sample name, must be of same length as the input files.
      multiple_sep: ";"
    - name: "--type"
      type: string
      required: false
      multiple: true
      example: Sample
      description: Sample type, must be of same length as the input files.
      choices: [Sample, Standard, QC, Blank]
      multiple_sep: ";"
    - name: "--class_id"
      type: string
      required: false
      multiple: true
      example: ["1", "2", "3"]
      description: Sample class, must be of same length as the input files.
      multiple_sep: ";"
    - name: "--batch"
      type: integer
      required: false
      multiple: true
      example: [1,2,3]
      description: Sample batch, must be of same length as the input files.
      multiple_sep: ";"
    - name: "--analytical_order"
      type: integer
      required: false
      multiple: true
      example: [2,1,3]
      description: Sample analytical order, must be of same length as the input files.
      multiple_sep: ";"
    - name: "--inject_volume"
      type: double
      required: false
      multiple: true
      example: [1.0, 0.9, 1.1]
      description: Sample injection volume in µL, must be of same length as the input files.
      multiple_sep: ";"
      
    # data type args
    - name: "--data_type"
      type: string
      choices: [Centroid, Profile]
      default: Centroid
    - name: "--ion_mode"
      type: string
      choices: [Positive, Negative]
      default: Positive
    - name: "--accuracy_type"
      type: string
      choices: [IsNominal, IsAccurate]
      default: IsNominal
    
    # data collection parameters
    - name: "--retention_time_begin"
      type: integer
      default: 0
    - name: "--retention_time_end"
      type: integer
      default: 25
    - name: "--mass_range_begin"
      type: integer
      default: 0
    - name: "--mass_range_end"
      type: integer
      default: 1000
    
    # peak detection parameters
    - name: "--smoothing_method"
      type: string
      choices: [SimpleMovingAverage, LinearWeightedMovingAverage, SavitzkyGolayFilter, BinomialFilter]
      default: LinearWeightedMovingAverage
    - name: "--smoothing_level"
      type: integer
      default: 3
    - name: "--average_peak_width"
      type: integer
      default: 20
    - name: "--minimum_peak_height"
      type: integer
      default: 1000
    - name: "--mass_slice_width"
      type: double
      default: 0.1
    - name: "--mass_accuracy"
      type: double
      default: 0.025

    # MS1Dec parameters
    - name: "--sigma_window_value"
      type: double
      default: 0.5
    - name: "--amplitude_cutoff"
      type: integer
      default: 10

    # identification parameters
    - name: "--msp_file"
      type: file
      required: false
      example: file.msp
    - name: "--ri_index_file"
      type: file
      required: false
      example: ri_index.txt
    - name: "--retention_type"
      type: string
      choices: [RI, RT]
      default: RI
    - name: "--ri_compound"
      type: string
      choices: [Fames, Alkanes]
      default: Alkanes
    - name: "--retention_time_tolerance_for_identification"
      type: double
      default: 0.5
    - name: "--retention_index_tolerance_for_identification"
      type: integer
      default: 20
    - name: "--ei_similarity_tolerance_for_identification"
      type: integer
      default: 70
    - name: "--identification_score_cutoff"
      type: integer
      default: 70

    # alignment parameters
    - name: "--alignment_index_type"
      type: string
      choices: [RI, RT]
      default: RT
    - name: "--retention_time_tolerance_for_alignment"
      type: double
      default: 0.075
    - name: "--retention_index_tolerance_for_alignment"
      type: integer
      default: 20
    - name: "--ei_similarity_tolerance_for_alignment"
      type: integer
      default: 70
    - name: "--retention_time_factor_for_alignment"
      type: double
      default: 0.5
    - name: "--ei_similarity_factor_for_alignment"
      type: double
      default: 0.5
    - name: "--peak_count_filter"
      type: integer
      default: 0
    - name: "--qc_at_least_filter"
      type: boolean
      default: true
  argument_groups:
    - name: Inputs
      arguments: [ input, name, type, class_id, batch, analytical_order, inject_volume ]
    - name: Data type arguments
      arguments: [ data_type, ion_mode, accuracy_type ]
    - name: Data collection arguments
      arguments: [ retention_time_begin, retention_time_end, mass_range_begin, mass_range_end ]
    - name: Peak detection arguments
      arguments: [ smoothing_method, smoothing_level, average_peak_width, minimum_peak_height, mass_slice_width, mass_accuracy ]
    - name: MS1Dec arguments
      arguments: [ sigma_window_value, amplitude_cutoff ]
    - name: Identification arguments
      arguments: [ msp_file, ri_index_file, retention_type, ri_compound, retention_time_tolerance_for_identification, retention_index_tolerance_for_identification, ei_similarity_tolerance_for_identification, identification_score_cutoff]
    - name: Alignment arguments
      arguments: [ alignment_index_type, retention_time_tolerance_for_alignment, retention_index_tolerance_for_alignment, ei_similarity_tolerance_for_alignment, retention_time_factor_for_alignment, ei_similarity_factor_for_alignment, peak_count_filter, qc_at_least_filter ]
  resources:
    - type: python_script
      path: script.py
  tests:
    - type: bash_script
      path: run_test.sh
    - path: ../../../resources_test/msdial_demo_files/raw/GCMS
platforms:
  - type: docker
    image: python:3.10
    setup:
      - type: apt
        packages: [ libnetcdf-dev ] # dependency of msdial
      - type: docker
        run: 
          # - mkdir /tmp/msdial && cd /tmp/msdial &&
          #   wget "http://prime.psc.riken.jp/compms/msdial/download/repository/Linux/MSDIAL%20ver.4.90%20Linux.zip" -O "msdial.zip" &&
          #   unzip "msdial.zip" && 
          #   mv "MSDIAL ver.4.90 Linux" /msdial &&
          #   rm -rf /tmp/msdial &&
          #   chmod +x /msdial/MsdialConsoleApp
          - mkdir /tmp/msdial && cd /tmp/msdial &&
            wget -q https://www.dropbox.com/s/zebtsivwrqt2dre/MSDIAL%20build%20Linux.zip?dl=1 -O "msdial.zip" &&
            unzip "msdial.zip" -d /msdial && 
            rm -rf /tmp/msdial && 
            chmod +x /msdial/MsdialConsoleApp
      - type: python
        pypi: pandas
  - type: nextflow
    variant: vdsl3