name: viash test CI

on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ '*' ]

# Skip older CI runs for pull requests (head_ref exists), otherwise allways build
# https://docs.github.com/en/actions/using-jobs/using-concurrency#example-using-a-fallback-value
concurrency: 
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  # phase 1
  list_components:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    steps:
    - uses: actions/checkout@v2

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    # create cachehash key
    - name: Create hash key
      id: cachehash
      run: |
        AWS_EC2_METADATA_DISABLED=true aws s3 ls s3://czbiohub-pipelines/resources_test_ms/ --recursive --no-sign-request > bucket-contents.txt
        CACHEHASH=resources_test_$( md5sum bucket-contents.txt | awk '{ print $1 }' )
        echo "Hash: $CACHEHASH"
        echo "::set-output name=cachehash::$CACHEHASH"
    
    # initialize cache
    - name: Cache resources data
      uses: actions/cache@v3
      with:
        path: resources_test
        key: ${{ steps.cachehash.outputs.cachehash }}

    # sync if need be
    - name: Sync test resources
      run: |
        bin/viash run \
          -p native \
          src/download/sync_test_resources/config.vsh.yaml \
          -- \
          --delete
        tree resources_test/ -L 3

    # store component locations
    - id: set_matrix
      run: |
        echo "::set-output name=matrix::$( bin/viash ns list -p docker --format json | jq -c '[ .[] | .info.config ]' )"
    outputs:
      matrix: ${{ steps.set_matrix.outputs.matrix }}
      cachehash: ${{ steps.cachehash.outputs.matrix }}

  # phase 2
  viash_test:
    needs: list_components

    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"

    strategy:
      fail-fast: false
      matrix:
        component_path: ${{ fromJson(needs.list_components.outputs.matrix) }}

    steps:
    - uses: actions/checkout@v2

    - name: Fetch viash
      run: |
        bin/init
        bin/viash -h

    # use cache
    - name: Cache resources data
      uses: actions/cache@v3
      with:
        path: resources_test
        key: ${{ needs.list_components.outputs.cachehash }}

    # sync if need be
    - name: View test resources
      run: |
        tree resources_test/ -L 3

    - name: Run test
      run: |
        bin/viash test -p docker ${{ matrix.component_path }}

